# Generated by Django 5.1.3 on 2024-12-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='stock_status',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
