# Generated by Django 5.1.3 on 2024-12-29 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_address', to='address.districtmodel'),
        ),
        migrations.AddField(
            model_name='districtmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_division', to='address.divisionmodel'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_address', to='address.divisionmodel'),
        ),
        migrations.AddField(
            model_name='hubmodel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_district', to='address.districtmodel'),
        ),
        migrations.AddField(
            model_name='subdistrictmodel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_district_district', to='address.districtmodel'),
        ),
        migrations.AddField(
            model_name='subdistrictmodel',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_district_division', to='address.divisionmodel'),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thana_address', to='address.subdistrictmodel'),
        ),
    ]
