# Generated by Django 5.1.3 on 2024-12-29 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'cash'), ('BKASH', 'bkash')], default='CASH', max_length=50, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('total_weight', models.FloatField(blank=True, help_text='Total weight of the order (in grams)', null=True)),
                ('ask_delivery_fee', models.FloatField(blank=True, null=True)),
                ('actual_delivery_fee', models.FloatField(blank=True, null=True)),
                ('delivery_profit', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('delivery_duration', models.TextField(blank=True, null=True)),
                ('delivery_tracker', models.URLField(blank=True, null=True)),
                ('delivery_status', models.TextField(blank=True, help_text='Delivery status (for customers)', max_length=100, null=True)),
                ('order_status', models.CharField(blank=True, choices=[('PROCESSING', 'processing'), ('CONFIRMED', 'confirmed'), ('IN_TRANSIT', 'in_transit'), ('DELIVERED', 'delivered'), ('CANCELLED', 'cancelled'), ('RETURNED', 'returned')], help_text='Order status (for admin)', max_length=100, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('alter_status', models.BooleanField(blank=True, default=True, null=True)),
                ('voucher_amount', models.FloatField(blank=True, default=0, null=True)),
                ('order_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_payment_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderReviewModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('review_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_review_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('minimum_amount', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'cash'), ('BKASH', 'bkash')], default='CASH', max_length=50, null=True)),
                ('voucher_type', models.CharField(blank=True, choices=[('STARTER', 'starter'), ('REGULAR', 'regular'), ('PREMIUM', 'premium'), ('GENERAL', 'general')], max_length=50, null=True)),
                ('is_free', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'voucher_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItemModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, help_text='Total cost for each item', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Total weight for each item', null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_item', to='product_management.productmodel')),
            ],
            options={
                'db_table': 'cart_item_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text="Unique id for a model's object", primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text="Is the model's object active")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text="Creation date of the model's object")),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text="Updating date of the model's object")),
                ('cart_status', models.BooleanField(blank=True, default=False, null=True)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_hub', to='address.hubmodel')),
            ],
            options={
                'db_table': 'cart_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
