# Generated by Django 5.1.3 on 2024-12-29 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_initial'),
        ('order_management', '0001_initial'),
        ('product_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_cart', to='order_management.cartmodel'),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_address', to='address.addressmodel'),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_cart', to='order_management.cartmodel'),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment_hub', to='address.hubmodel'),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderreviewmodel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_review_order', to='order_management.orderpaymentmodel'),
        ),
        migrations.AddField(
            model_name='orderreviewmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_review_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchermodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_item', to='product_management.productmodel'),
        ),
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_management.vouchermodel'),
        ),
    ]
