# Generated by Django 5.1.3 on 2024-12-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymentmodel',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
