# Generated by Django 5.1.3 on 2025-01-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_remove_orderpaymentmodel_alter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymentmodel',
            name='cart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
